# Generated by Django 3.0.5 on 2020-06-11 12:16

import clustering_questioner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='upload_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.FileField(upload_to=clustering_questioner.models.path_and_rename)),
            ],
        ),
    ]
