# Generated by Django 3.0.5 on 2020-06-11 16:45

import clustering_questioner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering_questioner', '0002_auto_20200611_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='isi',
            field=models.FileField(upload_to=clustering_questioner.models.path_and_rename),
        ),
    ]
