# Generated by Django 3.0.5 on 2020-06-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering_questioner', '0003_auto_20200611_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='isi',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
