# Generated by Django 3.0.5 on 2020-06-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clustering_questioner', '0004_auto_20200612_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload_data',
            name='isi',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
